### ISSUE TITLE
add better error handling to ERC721AccessControl and ERC20AccessControl

### ISSUE THREAD

**Issue by 0xTranqui** [public-assembly/onchain#12]
@SweetmanTech tagging u in this cuz need to add it to the ERC721 one as well. Need to update the error handling in the "getAccessLevel" call to make sure that if accessControl hasnt been initialized for a specific contract yet, it has a revert/error that handles it cleanly

currently:
<img width="643" alt="Screen Shot 2022-10-30 at 9 06 19 PM" src="https://user-images.githubusercontent.com/93691906/198928842-a721bdfc-1e6e-4b38-8cd6-82e60af9b074.png">

should be something like:
- one big try/catch decision tree that checks to see if the accessControl has been set up, and if yes goes through the stages of checking for admin -> manager -> curator access, with a clean fail state provided for each one for wtv reason that read may fail

**Comment by sweetmantech** [comment]
seeing this now 👀 

We definitely wanna check if `curatorAccess != address(0)` and `curatorMinimumBalance != 0`. ✅ 
- writing up a second PR for this now. ✏️ 

question: do we need to check anything beyond that?
- `address(info.managerAccess) == address(0)` - what if I don't want a manager contract so I set it to `address(0)`?
- `info.managerMinimumBalance != 0` - same question. ⬆️ 
- same for Admin. I might not want an admin for curation right?

Curious your thoughts on more checks that that. 💭 🤔

**Comment by sweetmantech** [comment]
Opened a PR: https://github.com/public-assembly/onchain-modules/pull/14

Please merge this PR first to reduce delta: https://github.com/public-assembly/onchain-modules/pull/13

@0xTranqui ⬆️
